FROM node:22 AS build

WORKDIR /app

COPY backend/package.json backend/yarn.lock ./

RUN yarn install --frozen-lockfile

COPY backend .

RUN yarn build

#  ----------------------------------------------------
FROM node:22-alpine AS prod

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json /app/yarn.lock ./

RUN yarn install --production --frozen-lockfile

EXPOSE 3000

CMD ["node", "dist/src/main"]